# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: pets
      MYSQL_USER: sergioc
      MYSQL_PASSWORD: sergioc